apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "assets.fullname" . }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- toYaml .Values.labels | nindent 4 }}
