{{- if .Values.serviceAccount.create -}}
apiVersion: {{ .Values.service.apiVersion }}
kind: ServiceAccount
metadata:
  name: {{ include "assets.fullname" . }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
{{- end }}
